<?php

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$assetUrl = $plugins->get('assetUrl');

$this->htmlElement('body')->appendAttribute('class', 'settings edit');

$this->headLink()->appendStylesheet($assetUrl('css/settings.css', 'RolesManager'));
$this->headScript()->appendFile($assetUrl('js/settings.js', 'RolesManager'), 'text/javascript', ['defer' => 'defer']);

$maintenance = [];
if ($this->userIsAllowed('RolesManager\Controller\Admin\ImportController', 'import')){
    $maintenance[$translate('Import')] = $this->url('admin/roles-manager-import', ['action' => 'import']);
}
if ($this->userIsAllowed('RolesManager\Controller\Admin\SettingsController', 'backups')){
    $maintenance[$translate('Backups')] = $this->url('admin/roles-manager-settings', ['action' => 'backups']);
}
if ($this->userIsAllowed('RolesManager\Controller\Admin\SettingsController', 'uprules')){
    $maintenance[$translate('Update rules')] = $this->url('admin/roles-manager-settings', ['action' => 'uprules']);
}
if ($this->userIsAllowed('RolesManager\Controller\Admin\SettingsController', 'updoctrine')){
    $maintenance[$translate('Update Doctrine')] = $this->url('admin/roles-manager-settings', ['action' => 'updoctrine']);
}
if ($this->userIsAllowed('RolesManager\Controller\Admin\SettingsController', 'uplocaletpl')){
    $maintenance[$translate('Update Locale template')] = $this->url('admin/roles-manager-settings', ['action' => 'uplocaletpl']);
}

$form->prepare();
?>
<?= $this->pageTitle($translate('Settings'), 1, $translate('Roles Manager')) ?>
<?= $this->form()->openTag($form) ?>

<div id="page-actions">
    <?php if (!empty($maintenance)): ?>
        <?php if (count($maintenance) > 1): ?>
    <a href="#" id="expand-menu" class="collapsed button expand-more" aria-label="<?= $translate('Maintenance') ?>" title="<?= $translate('Maintenance') ?>" aria-expanded="false" aria-target="#maintenance-menu"><?= $translate('Maintenance') ?></a>
    <ul id="maintenance-menu" class="collapsible-menu">
        <?php foreach ($maintenance as $title => $url): ?>
        <li>
            <a href="<?= $url ?>" class="link"><?= $title ?></a>
        </li>
        <?php endforeach; ?>
    </ul>
        <?php else: ?>
            <a href="<?= current($maintenance) ?>" class="button"><?= key($maintenance) ?></a>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($this->userIsAllowed('RolesManager\Controller\Admin\RoleController', 'browse')): ?>
        <?= $hyperlink($translate('Roles'), $this->url('admin/roles', []), ['class' => 'button']) ?>
    <?php endif; ?>
    <button type="submit"><?= $translate('Save') ?></button>
</div>

<?= $this->formCollection($form, false) ?>
<?= $this->form()->closeTag() ?>
