<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \RolesManager\Form\PermissionForm $form
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->htmlElement('body')->appendAttribute('class', 'roles backup');
?>

<?= $this->pageTitle($translate('Backups'), 1, $translate('Roles Manager')) ?>

<div id="page-actions">
    <?= $hyperlink($translate('Roles'), $this->url('admin/roles', []), ['class' => 'button']) ?>
    <?= $hyperlink($translate('Configure'), $this->url('admin/roles-manager-settings', ['action' => 'edit']), ['class' => 'button']) ?>
    <?= $hyperlink($translate('Backups'), $this->url('admin/roles-manager-settings', ['action' => 'backup'], true), ['class' => 'button']) ?>
</div>
<fieldset id="general" class="section active"></fieldset>
<?php
foreach($result as $k => $v){
    echo $k.' - '.$v.'<br>';
}
?>
</fieldset>