<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->htmlElement('body')->appendAttribute('class', 'roles');
?>

<?= $this->pageTitle($translate('TEST'), 1, $translate('Roles')) ?>

<div id="page-actions">
    <?= $hyperlink($translate('Roles'), $this->url('admin/roles', []), ['class' => 'button']) ?>
    <?= $hyperlink($translate('Configure'), $this->url('admin/roles-manager-settings', ['action' => 'edit']), ['class' => 'button']) ?>
</div>
<fieldset id="general" class="section active"></fieldset>
<pre>
<?php
print_r($result);
?>
</pre>