<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \RolesManager\Api\Representation\RoleRepresentation[] $resources
 * @var \RolesManager\Api\Representation\RoleRepresentation[] $groups
 * @var array $roleCount
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$assetUrl = $plugins->get('assetUrl');

$this->htmlElement('body')->appendAttribute('class', 'roles browse');

$this->headLink()->appendStylesheet($assetUrl('css/roles.css', 'RolesManager'));
$this->headScript()->appendFile($assetUrl('js/roles.js', 'RolesManager'), 'text/javascript', ['defer' => 'defer']);

$sortHeadings = [
    [
        'label' => $translate('Name'),
        'value' => 'name',
    ],
    [
        'label' => $translate('Label'),
        'value' => 'label',
    ],
    [
        'label' => $translate('Total users'),
        'value' => 'users',
    ],
];
$createRight = $this->userIsAllowed('RolesManager\Controller\Admin\RoleController', 'add');
// $editRight = $this->userIsAllowed('RolesManager\Controller\Admin\RoleController', 'update');
$deleteRight = $this->userIsAllowed('RolesManager\Controller\Admin\RoleController', 'delete');
// $batchDeleteRight = $this->userIsAllowed('RolesManager\Controller\Admin\RoleController', 'batch-delete');
$batchDeleteRight = False;

?>

<?= $this->pageTitle($translate('Roles')) ?>

<?= $this->searchFilters() ?>

 <div class="browse-controls">
    <?= $this->pagination() ?>
    <?php // echo $hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>
    <?= $this->sortSelector($sortHeadings) ?>
</div>

<form method="post" id="batch-form" class="disable-unsaved-warning">

<div id="page-actions">
    <?php if ($this->userIsAllowed('RolesManager\Controller\Admin\ImportController', 'import')): ?>
        <a href="<?= $this->url('admin/roles-manager-import', ['action' => 'browse']) ?>" class="button"><?= $translate('Import') ?></a>
    <?php endif; ?>
    <?php if ($this->userIsAllowed('RolesManager\Controller\Admin\RoleController', 'change-native') && $nativeRoles): ?>
    <?= $hyperlink($translate('Change native'), $this->url('admin/roles', ['action' => 'mod'],), ['class' => 'button']) ?>
    <?php endif; ?>
    <?php if ($createRight): ?>
    <?= $hyperlink($translate('Add'), $this->url('admin/roles', ['action' => 'add']), ['class' => 'button']) ?>
    <?php endif; ?>
<?php if ($roles): ?>
    <?php if ($batchDeleteRight): ?>
    <a href="#"
        class="button delete batch-actions sidebar-content"
        data-sidebar-content-url="<?= $escape($this->url(null, ['action' => 'batch-delete-confirm'])) ?>"
        aria-label="<?= $escape($translate('Delete')) ?>"
        title="<?= $escape($translate('Delete')) ?>"><?= $escape($translate('Delete')) ?></a>
    <?php endif; ?>
<?php endif; ?>
    <?php if ($this->userIsAllowed('RolesManager\Controller\Admin\SettingsController', 'edit')): ?>
        <a href="<?= $this->url('admin/roles-manager-settings', ['action' => 'edit']) ?>" class="button"><?= $translate('Configure') ?></a>
    <?php endif; ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<?php if (empty($roles)): ?>
<div class="no-resources">
    <p><?= $translate('There are no roles.') ?></p>
</div>
<?php $this->trigger('view.browse.after'); ?>

<?php else: ?>
<table class="tablesaw <?php if ($batchDeleteRight) echo 'batch-edit'; ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th class="column-role">
                <?php if ($batchDeleteRight): ?>
                <input type="checkbox" class="select-all">
                <?php endif; ?>
                <?= $translate('Name') ?>
            </th>
            <th><?= $translate('Label') ?></th>
            <th><?= $translate('Users') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($roles as $role):
            $name = $role->name();
        ?>
        <tr>
            <td>
                <?php if ($batchDeleteRight && (!$role->created() || ($role->created() && empty($role->countUser())))): ?>
                    <input type="checkbox" name="resource_ids[]" value="<?= $role->id() ?>">
                <?php endif; ?>
                <span class="role-name<?= $role->active() ? '' : ' role-deactivated' ?>" ><?= $name; ?></span>
                <ul class="actions">
                    <?php if ($role->userIsAllowed('update')): ?>
                    <li><a href="<?= $this->url('admin/roles', ['action' => 'edit', 'id' => $role->id()]) ?>"
                        class="o-icon-edit"
                        aria-label="<?= $escape($translate('Edit name')) ?>"
                        title="<?= $escape($translate('Edit name')) ?>"></a></li>
                    <?php endif; ?>
                    <?php if ($role->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        class="o-icon-delete sidebar-content"
                        data-sidebar-content-url="<?= $escape($role->url('delete-confirm')) ?>"
                        aria-label="<?= $escape($translate('Delete')) ?>"
                        title="<?= $escape($translate('Delete')) ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?= $escape($role->url('show-details')) ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?= $escape($translate('Details')) ?>"
                        title="<?= $escape($translate('Details')) ?>"></a></li>
                </ul>
            </td>
            <td>
                <span class="role-label"><?= $translate($role->label()); ?></span>
            </td>
            <td><?php if (!empty($role->countUser())){ echo $hyperlink($role->countUser(), $role->urlToUsers(), ['class' => 'role-browse-user']); } ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?= $this->pagination() ?>
</div>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?= $escape($translate('Close')) ?>"
        title="<?= $escape($translate('Close')) ?>"></a>
    <div class="sidebar-content"></div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('.sidebar').on('submit', '#batch-delete-confirm', function(e) {
    var confirmForm = $(this);
    if (confirmForm.hasClass('batch-delete-all')) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input:checked').each(function() {
            confirmForm.append($(this).clone().attr('type', 'hidden'));
        });
    }
});
</script>
<?php endif; ?>
