<?php

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->htmlElement('body')->appendAttribute('class', 'configure');

$form->prepare();
?>
<?= $this->pageTitle($translate('Prepare for import'), 1, $translate('Roles Manager')) ?>
<?= $this->form()->openTag($form) ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed('RolesManager\Controller\Admin\RoleController', 'browse')): ?>
        <?= $hyperlink($translate('Roles'), $this->url('admin/roles', []), ['class' => 'button']) ?>
    <?php endif; ?>
    <?= $hyperlink($translate('Configure'), $this->url('admin/roles-manager-settings', ['action' => 'edit']), ['class' => 'button']) ?>
    <?php echo $this->cancelButton(); ?>
    <button type="submit"><?= $translate('Save') ?></button>
</div>

<?= $this->formCollection($form, false) ?>
<?= $this->form()->closeTag() ?>

<?PHP
    if(!empty($result)){
        echo '<pre>';
        print_r($result);
        echo '</pre>';
    }
?>
