<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Group\Form\GroupForm $form
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$assetUrl = $plugins->get('assetUrl');

$this->htmlElement('body')->appendAttribute('class', 'roles add');

$this->headScript()->appendFile($assetUrl('js/roles-add.js', 'RolesManager'), 'text/javascript', ['defer' => 'defer']);

$form->prepare();
echo $this->pageTitle($translate('New role'), 1, $translate('Roles'));
echo $this->form()->openTag($form);
?>

<div id="page-actions">
    <?php echo $this->cancelButton(); ?>
    <button type="submit"><?= $translate('Add') ?></button>
</div>

<?PHP
echo $this->formCollection($form, false);
echo $this->form()->closeTag();
?>
