<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->htmlElement('body')->appendAttribute('class', 'roles import');
?>

<?= $this->pageTitle($translate('Import'), 1, $translate('Roles Manager')) ?>

<div id="page-actions">
    <?= $hyperlink($translate('Roles'), $this->url('admin/roles', []), ['class' => 'button']) ?>
    <?= $hyperlink($translate('Configure'), $this->url('admin/roles-manager-settings', ['action' => 'edit']), ['class' => 'button']) ?>
    <?= $hyperlink($translate('Upload'), $this->url('admin/roles-manager-settings', ['action' => 'uploadimpfile']), ['class' => 'button']) ?>
</div>


<?php if (empty($list)): ?>
<div class="no-resources">
    <p><?= $translate('Files for importing no found.') ?></p>
</div>

<?php else: ?>
<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $translate('Name') ?></th>
            <th><?= $translate('Actions') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($list as $file):
            $pathinfo = pathinfo($file);
        ?>
        <tr>
            <td>
                <span class="list-name"><?= $pathinfo['basename'] ?></span>
            </td>
            <td>
            <ul class="actions">
                    <li><a href="#"
                        class="o-icon-edit fa-reply sidebar-content"
                        data-sidebar-content-url="<?= $escape($this->url('admin/roles', ['action' => 'import-confirm', 'name' => $pathinfo['basename']])) ?>"
                        aria-label="<?= $escape($translate('Import')) ?>"
                        title="<?= $escape($translate('Import')) ?>"></a></li>
                    <li><a href="#"
                        class="o-icon-delete sidebar-content"
                        data-sidebar-content-url="<?= $escape($this->url('admin/roles', ['action' => 'delete-impfile-confirm', 'name' => $pathinfo['basename']])) ?>"
                        aria-label="<?= $escape($translate('Delete')) ?>"
                        title="<?= $escape($translate('Delete')) ?>"></a></li>
                </ul>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?= $escape($translate('Close')) ?>"
        title="<?= $escape($translate('Close')) ?>"></a>
    <div class="sidebar-content"></div>
</div>

<?php endif; ?>
