<?php
$common = $this->ItemsReviewCommon();

$defaultSiteId = $this->setting('default_site');

$translate = $this->plugin('translate');
$title = $this->setting('installation_title', 'Omeka S');
echo $this->pageTitle($translate('Admin dashboard'));

// if($common->roleIsContributor() && isset($myItemCount)){
//     $itemCount = $myItemCount.'\\'.$itemCount;
//     if($allowedItemSetsCount !== $itemSetCount){
//         $itemSetCount = $allowedItemSetsCount.'\\'.$itemSetCount;
//     }
// }
?>

<div id="dashboard">
    <?php echo $this->partial('common/version-notification'); ?>
    <p><?php echo sprintf($translate('Welcome to the %s admin dashboard!'), $this->escapeHtml($title)); ?></p>
    <?php $this->trigger('view.browse.before'); ?>
    <div id="manage-resources" class="panel">
        <h2><?php echo $translate('Manage resources'); ?></h2>
        <?php $this->trigger('view.manage_resources.before'); ?>
        <?php if ($this->userIsAllowed('Omeka\Controller\Admin\Item', 'browse')): ?>
        <div class="items resource row">
            <?php echo $this->hyperlink($translate('Items').' ('.$itemCount.')', $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'])); ?>
            <?php if ($this->userIsAllowed('Omeka\Api\Adapter\ItemAdapter', 'create')): ?>
            <?php echo $this->hyperlink('', $this->url('admin/default', ['controller' => 'item', 'action' => 'add']), ['class' => 'add button', 'title' => $translate('Add new item')]); ?>
            <?php endif; ?>
        </div>
        <?php endif; ?>
        <?php if ($this->userIsAllowed('Omeka\Controller\Admin\ItemSet', 'browse')): ?>
        <div class="item-sets resource row">
            <?php echo $this->hyperlink(sprintf($translate('Item sets (%s)'), $itemSetCount), $this->url('admin/default', ['controller' => 'item-set', 'action' => 'browse'])); ?>
            <?php if ($this->userIsAllowed('Omeka\Api\Adapter\ItemSetAdapter', 'create')): ?>
            <?php echo $this->hyperlink('', $this->url('admin/default', ['controller' => 'item-set', 'action' => 'add']), ['class' => 'add button', 'title' => $translate('Add new item set')]); ?>
            <?php endif; ?>
        </div>
        <?php endif; ?>
        <?php if ($this->userIsAllowed('Omeka\Controller\Admin\Vocabulary', 'browse')): ?>
        <div class="vocabularies resource row">
            <?php echo $this->hyperlink(sprintf($translate('Vocabularies (%s)'), $vocabularyCount), $this->url('admin/default', ['controller' => 'vocabulary', 'action' => 'browse'])); ?>
            <?php if ($this->userIsAllowed('Omeka\Api\Adapter\VocabularyAdapter', 'create')): ?>
            <?php echo $this->hyperlink('', $this->url('admin/default', ['controller' => 'vocabulary', 'action' => 'import']), ['class' => 'add button', 'title' => $translate('Import new vocabulary')]); ?>
            <?php endif; ?>
        </div>
        <?php endif; ?>
        <?php if ($this->userIsAllowed('Omeka\Controller\Admin\ResourceTemplate', 'browse')): ?>
        <div class="resource-templates resource row">
            <?php echo $this->hyperlink(sprintf($translate('Resource templates (%s)'), $resourceTemplateCount), $this->url('admin/default', ['controller' => 'resource-template', 'action' => 'browse'])); ?>
            <?php if ($this->userIsAllowed('Omeka\Api\Adapter\ResourceTemplateAdapter', 'create')): ?>
            <?php echo $this->hyperlink('', $this->url('admin/default', ['controller' => 'resource-template', 'action' => 'add']), ['class' => 'add button', 'title' => $translate('Add new resource template')]); ?>
            <?php endif; ?>
        </div>
        <?php endif; ?>
        <?php $this->trigger('view.manage_resources.after'); ?>
    </div>

<?php if(!empty($sites)): ?>
    <div id="manage-sites" class="panel">
        <h2><?php echo $translate('Sites'); ?></h2>
        <?php $this->trigger('view.manage_sites.before'); ?>
        <?php foreach ($sites as $site): ?>
        <div class="site row">
            <span class="site-name">
                <?php if ($this->userIsAllowed('Omeka\Controller\SiteAdmin\Index', 'index')): ?>
                <?php echo $site->link($site->title(), 'show'); ?>
                <?php else: ?>
                <?= $site->title() ?>
                <?php endif; ?>
            </span>
            <?php
            // if(!empty($defaultSiteId) && $defaultSiteId == $site->id()){
                // $siteUrl = '/';
            // }else{
                $siteUrl = $site->siteUrl(Null, True);
            // }
            echo $this->hyperlink('', $siteUrl, [
                'target' => '_blank',
                'class' => 'o-icon-external public button',
                'title' => $translate('View public site'),
            ]);
            ?>
        </div>
        <?php endforeach; ?>
        <?php if ($this->userIsAllowed('Omeka\Entity\Site', 'create')): ?>
        <?php echo $this->hyperlink($translate('Add site'), $this->url('admin/site/add'), ['class' => 'add button']); ?>
        <?php endif; ?>
    <?php $this->trigger('view.manage_sites.after'); ?>
    </div>
<?php endif; ?>
<?php $this->trigger('view.browse.after'); ?>
</div>